### ISSUE TITLE
Requires Glad

### ISSUE THREAD

**Issue by Gazoo101** [axjxwright/AX-MediaPlayer#2]
Providing AX-MediaPlayer to Cinder as a block appears to work like a treat. However, it seems a 3rd party library, namely `glad`, is required. I'd suggest adding it as some sort of requirement in the CMake file.

As you know by our cinder forum chats, I'm pretty much a CMake novice, so I don't know how best to add this requirement in a CMake file that is to be parsed by Cinder. All I know is that if I needed Glad in my own project, I'd install it using vcpkg, and then call `find_package(glad REQUIRED)` or something similar.

**Comment by axjxwright** [comment]
Glad comes with cinder, what version are you compiling against?

**Comment by axjxwright** [comment]
Looks like glad was added for cinder_0.9.3, before that it was using glload. 

In the meantime you can replace the glad include with `#include "glload/wgl_all.h"` and i'll work out a way to detect the cinder version and alter the include accordingly

**Comment by axjxwright** [comment]
Ok, [this commit](https://github.com/axjxwright/AX-MediaPlayer/commit/23a5056f0768ee1836a32e3953a041c81fa6f017) detects the cinder version being used and includes the appropriate GL loader, please let me know if that does the trick when you get a chance. Ta

**Comment by Gazoo101** [comment]
While I've not had a chance to add code that actively displays a decoded video texture, I have now managed to compile, link, and at least instantiate the player object and see it be successfully constructed.

Appreciate your patience. I've had more CMake barriers along the way, but I do believe that the vast majority is now behind me!

I'll post another update when I've seen some decoded textures in action - so far so good!

**Comment by axjxwright** [comment]
Good to hear, closing this for now since the glad/glload stuff seems to be sorted. Feel free to report any issues as you find them (time permitting, of course).

Thanks
