### ISSUE TITLE
Crash on wglDXUnregisterObjectNV()

### ISSUE THREAD

**Issue by clinthidinger** [axjxwright/AX-MediaPlayer#6]
I get a crash in  wglDXUnregisterObjectNV ( InteropContext::Get().Handle(), _shareHandle ); on line 241 of AX-MediaPlayerMSWDXGIRenderPath.cxx from the SimplePlaybackApp.  I believe there is an issue with deleting this handle after either DX or GL contexts have started to shutdown.   I should mention that I am testing this on Windows 11.

My current work-around is to add this inside SimplePlaybackApp::setup():

`
getWindow()->getSignalClose().connect( [this] {
        _player.reset(); 
    } );
`

**Comment by axjxwright** [comment]
Are you using an intel integrated card by any chance? I've seen this once or twice, but only on old intel cards with dubious implementations of the extension. I deliberately leak the DX context to make sure it always survives till the process ends but I guess a subtle difference in object lifetimes within the GL context could bring about this issue. Thanks for letting me know.

**Comment by clinthidinger** [comment]
You are right about that.  I am on a Surface Studio laptop that has a RTX 3050 and an Intel Iris card.  After explicitly setting the Nvidia Control Panel to use the "High Performance Nvidia Processor" for the app, the crash no longer happens.  Thanks for the tip.
